### ISSUE TITLE
Terminator separator size cannot be changed

### ISSUE THREAD

**Issue by mareksamec** [gnome-terminator/terminator#133]
In the past there was an issue where the separator could not be changed and was stuck to about 6px. Now it seems that no matter what value I set (from the range of -1 to 20) the separator width always remains 1px.

Here is the link for the previous issue reported on launchpad:
https://bugs.launchpad.net/terminator/+bug/1518069

**Some version info:**
terminator 1.92
GTK version 3.24.20
5.6.15-arch1-1

**Comment by mattrose** [comment]
@mareksamec do you know if the patch in the original LP bug has been applied, or can be applied cleanly?

**Comment by mattrose** [comment]
To answer my original questions:  Maybe, and definitely not.  That is not the problem though.  The problem is that the css property that we were exposing was deprecated as of GTK 3.20.  With a little help from the #python irc channel in the gnome IRC server I was able to figure out a fix, I just have to implement it outside of the GTK inspector now:

The CSS is:
```
separator { 
	min-height: 5px;
	min-width: 20px;
}
```

**Comment by mareksamec** [comment]
Great job, thank you for the quick resolution!
