### ISSUE TITLE
Duplication of Icons due to different WM_CLASS names

### ISSUE THREAD

**Issue by Ajith-stark** [gnome-terminator/terminator#177]
I have a Pined terminator to dash.  When press CTRL+ALT+T to open it creates a duplicate icon in the dash.
I tried adding this line` StartupWMClass=[x-terminal-emulator]` but didn't work.

**Comment by Ajith-stark** [comment]
It only happens while using short cut method
in below image, you can see 2 different names are used also you can see at top bar tab name ( next to activities thing )


![terminator-bug](https://user-images.githubusercontent.com/47944176/89121404-57411c80-d4dc-11ea-97de-d2dfcef6b8ca.png)

**Comment by mattrose** [comment]
Few questions.  I was unable to reproduce this using a bunch of different OSes and Desktop Environments.

What Window Manager/Desktop are you using? 
What OS are you using?

**Comment by Ajith-stark** [comment]
Ubuntu 18.04
Is this repo different from the terminator available in apt repo ( terminator/bionic,bionic,now 1.91-1) ?
if it is then this is something different.

reproduce:
- Close terminator app if already opened 
- Now press `CTRL+ALT+X` and terminator launches but the name of that tab is **x-terminator-emulator** ( you can see that' in previous post )
- Now close it.
- Now open terminator by clicking on icon in _show applications_ and now tab name is **terminator**
I added terminator to favorites ( added to dock ) so when it launches( via short cut ) it creates a separate icon instead of stacking on same icon.

**Comment by mattrose** [comment]
This is due to a glib problem.  For some reason, glib will let you have any default application for web browser, or email client, or whatever, but stock glib has a **hardcoded list of terminal emulators** that it looks through anytime you request a terminal.  Ubuntu works around this, but as you can see, it's kind of a hack.  https://gitlab.gnome.org/GNOME/glib/-/issues/338 has the bug, and https://gitlab.gnome.org/GNOME/glib/-/merge_requests/255 has some details of the hack.

Sorry.  I'm on Fedora and I don't even have this hack, so consider yourself lucky :)
