### ISSUE TITLE
Multi tab breaks transparent background

### ISSUE THREAD

**Issue by njZhuMin** [gnome-terminator/terminator#225]
Hi guys,
Thank you so much for almost bringing the very iTerm onto Linux. AMAZING work!

Here I'd like to report an issue.

Reproduce:
1. Set transparent background in Terminator
2. Open Terminator, transparent background works fine
3. Open a new tab by "Ctrl+Alt+T"
4. Switch between two tabs, or just click another window to make Terminator window lose focus
5. Transparent background does not work any more util reopen Terminator

Thanks.

**Comment by mattrose** [comment]
Found it.  PR incoming

**Comment by ynikitenko** [comment]
It seems I have the same problem with my config (https://github.com/gnome-terminator/terminator/issues/414#issuecomment-813062726). Not sure whether I shall open a new issue.
When I set background to transparent, sometimes it works, sometimes not (tabs are non-transparent). When I open and close terminator windows, they may become transparent. Otherwise I can have just blurred windows (with grey text), and terminal with black background is better.
