### ISSUE TITLE
Pls add version on OS X

### ISSUE THREAD

**Issue by smartmanru** [gnome-terminator/terminator#283]
Pls add version for Mac os X and create bottle on homebrew

**Comment by mattrose** [comment]
I'm actually running terminator on my macos desktop.  I would like to polish it up considerably before putting it in homebrew though for a couple of reasons.

1.  A lot of different keybindings require an upstream patch for VTE that hasn't been accepted.  I would have to fix up that patch considerably and add it to the vte3 homebrew package. See patch at https://gitlab.gnome.org/GNOME/vte/-/issues/249

2.  The integration with macos is, tbh, pretty crappy.  Each window just has a name of "Python" and each terminator window spawns a new process.  It's messy.

If you want to help out, I'd be glad to accept any pull requests.  You can get it running on macos right now, it's just not quite ready for prime-time yet.

**Comment by caioquirino** [comment]
Hi @mattrose do you have a fork that you are working on it? I was also working on it and started creating a brew bottle for the latest version as well

**Comment by mattrose** [comment]
Any work I do on terminator for OSX is merged into this repo, so you can get it here.  I'd love to see the brew bottle when you're done with it.

**Comment by mattrose** [comment]
Opened https://github.com/Homebrew/homebrew-core/pull/79647

This was actually easier than I thought.  The vte3 patch is no longer necessary, they must have fixed this recently. 

It is kind of a pain to use out of the box, because you need to open a terminal to start terminator.  This was mainly to comply with homebrew requirements (Don't ship a .app bundle).  What I've done personally is use [Platypus](https://sveinbjorn.org/platypus) to create an app from the terminator command line.

I might clean this up and put it on my personal github.

**Comment by caioquirino** [comment]
Hi @mattrose really nice work on it! I really wanted to help more, but I have replaced my macbook with a dell laptop :(
I hope it works well :) Cheers!

**Comment by carlocab** [comment]
You can now install this with (macOS) Homebrew. Try
```
brew update && brew install terminator
```
It should be available for Homebrew on Linux in the next day or so.

> It is kind of a pain to use out of the box, because you need to open a terminal to start terminator. This was mainly to comply with homebrew requirements (Don't ship a .app bundle). What I've done personally is use [Platypus](https://sveinbjorn.org/platypus) to create an app from the terminator command line.

Out of interest: does your build actually support generating an app bundle? Or do you build it with pip/python and then use Platypus?

**Comment by mattrose** [comment]
I build it with python then use Platypus for now.  I'm still trying to wrap my head around the osx specific stuff.  I think I need to generate an app bundle by hand and integrate with the GtkOSXApplication library.  Anytime I've tried this on my mac I end up lost and confused.  I use Macs on a daily basis, but this is my first time developing anything for the platform.

**Comment by mattrose** [comment]
Interesting story.  When Markus and I took over the project, I hadn't used a Linux desktop in years and was exclusively using MacOS.  I was happily using iTerm2 on MacOS, but I knew there was a bunch of people who used terminator and it made me sad to see it die due to lack of interest, so I agreed to maintain it with Markus. 
One of the first things I did was get terminator working on MacOS so I could hack on it without opening a VM, so in a way this is kind of a culmination of a year of effort.

When I was ready to go back to work, I found a job that required a linux desktop, so now I again have to use terminator on a daily basis.

**Comment by lhoguin** [comment]
Being able to run terminator on macOS is very nice. Great work!

Integration is messy for sure. It's even worse with the program I'm using that replaces Alt+Tab with a less application-centric equivalent: the terminal windows do not even show up. But I can probably live with that.

Window resizing is super slow, but at the same time it's not something that is often needed.

I can use Alfred to start a new terminator window directly, which is great. But like when I start terminator from the macOS terminal, the window originally appears behind the current window.

I will try to work with it in the coming days. This is very much appreciated!

**Comment by mattrose** [comment]
Wow, that was quick.  I have a hacky workaround for the fact that terminator seems to start in the background (Applescript to bring it to the front) which I can put here when I get back to my mac.  I haven't noticed window resizing being slow but I'll keep an eye on it.  Thanks for checking this out.  Any improvements you can make are extremely welcome.  Mac programming is not my forte.

**Comment by carlocab** [comment]
@mattrose that's a nice story! Guess that time you spent working on terminator paid off in the end.



> Anytime I've tried this on my mac I end up lost and confused. I use Macs on a daily basis, but this is my first time developing anything for the platform.

That's typical. The macOS user experience is great. The native developer experience, not so much.

**Comment by mattrose** [comment]
As promised, here's the applescript to bring the terminator window to the front.
```
    tell application "System Events"
        tell process "Python"
                set frontmost to true
        end tell
    end tell
```

**Comment by mattrose** [comment]
closing this, any further enhancements can be opened separately
