### ISSUE TITLE
How to install terminator without root privilege?

### ISSUE THREAD

**Issue by fanronghong** [gnome-terminator/terminator#332]
Hi all,

I want to install terminator on centos, but I have no root privilege. And I have troble with figuring out dependencies.
So is there any binary package which I can use for simple installation?
 
Thanks in advance!

**Comment by mattrose** [comment]
All I know for sure is what is in INSTALL.md. If you have `python3-gobject` (basically the python gobject-introspection libraries) and `vte291` you should be able to install the python dependencies through pip.

If you don't have any GTK libraries and want to run terminator, you could use [jhbuild](https://gitlab.gnome.org/GNOME/jhbuild) to install the GTK libraries, and then use pip to install python dependencies.

**Comment by zothar** [comment]
I did some playing on a Centos 7 LXC container and it looks like, assuming you already have all the needed RPMs installed to the target system (maybe the server admin won't mind missing ones mentioned in INSTALL.MD?), that this might work with a release tarball:

```
python3 setup.py build
python3 setup.py install --user
```
If you don't have gettext available, but do have everything else, then you'll want to use something like this with the current release (I believe the extra steps won't be needed if #342 is merged and the next release after that is available (or used the Download ZIP feature after merge)):

```
python3 setup.py --without-gettext build
cat data/terminator.desktop.in |sed "s%_%%" > data/terminator.desktop
cat data/terminator.appdata.xml.in |sed "s%_%%" > data/terminator.metainfo.xml
python3 setup.py --without-gettext install --user
```
Because of another issue I've not yet sorted out, you'll probably want to run terminator after one of the above installs in a weird way, with something like:

`~/.local/lib/python3.6/site-packages/terminator-2.0.1-py3.6.egg/EGG-INFO/scripts/terminator`

I'll caveat that I got it to install and run enough to tell me that I hadn't forwarded an X11 environment to that LXC container, so it may still complain about things I missed.

Looking at my history, these may get you past dependencies that don't have to be installed via RPM:

```
pip3 install --user pytest-runner
pip3 install --user pycairo
pip3 install --user psutil
```
