### ISSUE TITLE
Windows title are not udpated after ssh session disconnected

### ISSUE THREAD

**Issue by amsteel** [gnome-terminator/terminator#359]
Please try moving the terminator config out of the way to see if that solves the
problem.  If it does, and you still want to open the bug, then please attach the
config file to the issue

Fill out as many of these fields as you can

**Describe the bug**
The tile of the window is updated when connecting the ssh session. However the title remains the same after ssh session disconnected.

**To Reproduce**
1. start terminator
2. ssh to host1, title is updated to user@host1:...
3. type 'exit' to disconnect ssh session
4. title remains the same

**Expected behavior**
title should be updated after step 3

**Screenshots**

**Desktop (please complete the following information):**
 - OS or Linux Distribution: [e.g. FreeBSD or Ubuntu]
 - Version [e.g. 20.04]
Ubuntu 20.04

**Additional context**

**Comment by mattrose** [comment]
This is because when you SSH to a remote machine, the PS1 prompt gets updated, but when you logout of an SSH session, PS1 does not get updated.  This is common across all terminal emulators.  It annoys me too, but it's outside of the scope of the Terminal emulator.  If you can find a fix, let me know, I've found this on all terminal emulators I've used.

**Comment by amsteel** [comment]
Not related to the bug but simple google results surprise me as it was raised back about 10+ years ago. 
One trick to fix it is posted here (not sure if it is proper "fix" but works for me):

https://drone-ah.com/2020/06/25/how-to-terminal-title-after-disconnecting-from-ssh/

Tested with Ubuntu 20.04.
