### ISSUE TITLE
Clipboard commands

### ISSUE THREAD

**Issue by skerit** [gnome-terminator/terminator#366]
**Is your feature request related to a problem? Please describe.**

I used to use `xclip` over SSH in my terminal application to copy some text to the clipboard. Since switching to Wayland this is no longer possible, not even with `wl-clipboard` because Wayland doesn't have network transparency.

**Describe the solution you'd like**

The Kitty terminal actually supports a new terminal command: **clipboard_control**

In Kitty, you can set the clipboard value with this command: `printf "\033]52;;$(printf "%s" "blabla" | base64)\a"`

**Describe alternatives you've considered**

I tried `wl-clipboard`, but that doesn't work over SSH. I thought about just switching to Kitty, but it's not as user friendly as Terminator.

**Comment by mattrose** [comment]
Ugh, this is https://gitlab.gnome.org/GNOME/vte/-/issues/125 which seems to be a very contentious issue, and is currently closed, even though there is a perfectly good VTE patch that implements support for it just sitting there.  If I don't hear back soon I'll poke the VTE maintainer.

**Comment by mattrose** [comment]
Well, I'm really sorry, but given the response in https://bugzilla.gnome.org/show_bug.cgi?id=795774#c19 I'm going to say that VTE support for this is not going to be forthcoming.  I'll keep an eye on the issue, and I'll implement it in terminator if it ever gets supported, but I'm going to close this bug, because there's nothing I can do to fix this myself.

**Comment by skerit** [comment]
That's a shame. Thanks for looking into it though!
