### ISSUE TITLE
Terminal text isn't shown on lost focus of multiple tabs and hidden scroll bar

### ISSUE THREAD

**Issue by Syndamia** [gnome-terminator/terminator#372]
**Describe the bug**

When having multiple tabs open, the scrollbar is hidden on the currently opened tab and the terminal isn't in focus, the text in it isn't rendered.

**To Reproduce**

1. Open Terminator
2. Open another tab
3. Right-click and deselect "Show scrollbar"
4. Un-focus it, meaning click anywhere that isn't on the terminal

**Expected behavior**

When you click out of Terminator (when it isn't in focus), in all cases, it should still show the text in it.

**Screenshots**

![Peek 2021-01-21 15-36](https://user-images.githubusercontent.com/46843671/105358164-7ce2ef00-5bfe-11eb-97ac-720e09eb285b.gif)
*Here I show that it works as expected in all cases, except when the scroll bar is hidden and a tab is opened*

**Desktop (please complete the following information):**

 - OS or Linux Distribution: Fedora 33 (Cinnamon)
 - Terminator Version: 2.1.0

**Additional context**

<details>
<summary>My config file (although it shouldn't have anything that could cause this issue)</summary>

```
[global_config]
  focus = system
  handle_size = 1
  sticky = True
  suppress_multiple_term_dialog = True
[keybindings]
[profiles]
  [[default]]
    audible_bell = True
    background_color = "#282828"
    background_darkness = 0.95
    cursor_color = "#aaaaaa"
    font = MesloLGS NF 12
    foreground_color = "#ebdbb2"
    show_titlebar = False
    scrollback_infinite = True
    palette = "#282828:#cc241d:#98971a:#d79921:#458588:#b16286:#689d6a:#a89984:#928374:#fb4934:#b8bb26:#fabd2f:#83a598:#d3869b:#8ec07c:#ebdbb2"
    use_system_font = False
    background_image = /home/kamen/Desktop/2020-12-03_16-49.png
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
      profile = default
[plugins]
```

</details>

**Comment by mattrose** [comment]
Try removing `background_darkness` and `background_image` from your config file.  If that doesn't work, try rebuilding your default profile.  I have a feeling that something was going on with the dim on focus out stuff.  In your case it seems to be painting over the entire window.

**Comment by Syndamia** [comment]
> Try removing background_darkness and background_image from your config file.

Didn't work

> try rebuilding your default profile

Yeah, the default profile, that comes with it works fine, but that's because it has the scrollbar and title-bar (I just found out that it also affects it) shown. 

Even with stock settings, if you have multiple tabs, with hidden scroll bar and top bar, and you click off, the text disappears.

**Comment by mattrose** [comment]
You're right.  That is really weird.  I'm actually kinda stumped as to why it happens.  It only seems to be in that one configuration, which doesn't really make sense.  I'm gonna have to spend some time with this one.

**Comment by sr-crypsis** [comment]
Not sure if this issue is related, but I have noticed that having multiple panes open, the text/window doesn't update unless I click the terminator window. It will typically happen after a few commands are run and then switching to a different pane. For instance, if I have the window split vertically (two panes), I'll type some commands into the left one, switch to the right one and start typing, but the text doesn't appear. I can still run the commands but nothing will show up until I click into the window.

It doesn't seem to have this issue when I do not have the window split, i.e., just one standard window pane. I've only noticed this issue pop up within the last week or two and haven't really seen anything mentioned about it elsewhere.

Details (let me know if you'd need more info):
OS: Kali 2020.4
Terminator: 2.1.0
Shell: zsh

**Comment by mattrose** [comment]
Hmm, It might no be drawing the screen right away.  I think I finally figured out the cause of what was going on, but I'm just now trying to figure out how to fix it.  I think the dimming on focus out is a little too eager in what it paints over when there is no scrollbar or toolbar to box it in.  I still have to figure out how to give it the correct dimensions.

**Comment by hardaker** [comment]
Good news: I'm not insane.
Bad news: I see this behavior too.

For me, it's solely based on the visibility of the title bar (which I've always thought was a waste of space and turned it off (personal preference of course)).  The scrollbar toggling didn't help for me; only the title bar setting in the profile fixed it.  And thanks *very much* for this hint on what to change, because I was about to switch terminals.

**Comment by mattrose** [comment]
Ugh.  All right, I'll revert the code that does this and reopen #74.  It's a cosmetic change anyways, and it doesn't seem to work, so...  I'll push something out as soon as I can.

**Comment by mattrose** [comment]
Also, @hardaker I noticed that the bug is triggered depending on where you have the scrollbar.  If you have the scrollbar on the right, it stops it from happening.  If you have the scrollbar on the left, it doesn't stop if from happening.

**Comment by mattrose** [comment]
I've reverted the work I did for #74, which fixes this issue.  Please test this out by checking out master and running.  I think it's too soon to work up another release, but if anyone else comes across this they can grab the latest code.

**Comment by pipatron** [comment]
Thank you! The issue has annoyed me for months, but I can confirm that the commit solved the problem for me on Debian Testing/Gnome 3.38.3/Wayland

**Comment by edgan** [comment]
I feel like a new release, even for if just for this one issue, is warranted. I very nearly stopped using terminator, because of this bug. The only thing that stopped me is I couldn't find a good enough alternative. I started using terminator again after running into like bugs with tilix.

I did make my own Fedora 33 rpm with the necessary patch, but I bet there are 10 more people for everyone one that has compiled it themselves.

What is actually involved in making a new release? Is there a need for some automation? If so, I would be willing to help.

**Comment by mattrose** [comment]
I think you're right.  It's about time for a new release anyways, regardless of this bug.  I'll work on putting one out and getting it into F33 this week.

**Comment by jmechnich** [comment]
It would be great if this could make it into Debian Bullsye too if it is not too [late](https://release.debian.org/bullseye/freeze_policy.html)

**Comment by mattrose** [comment]
2.1.1 is out now. I can add it to Fedora, but I can't add things to Debian.  @lazyfrosch can, though. 😃

**Comment by habibendris10** [comment]
I have been struggling for some time but found a solution.
The only thing to do is to go to the **General** tab and set **Unfocused terminal font brightness** to **100%**.
This will set the brightness of a terminal when it is not focused.

**Comment by anurag-mehra** [comment]
I am also struggling something simillar just watch this video and you will understand text just disappers even when i am using the terminal

https://user-images.githubusercontent.com/72686000/158354769-06b6bca9-1135-4ba8-8932-802b5ffd7813.mp4

**Comment by Syndamia** [comment]
@anurag-mehra your issue seems to be completely different from mine, it might be a good idea to open a separate issue

**Comment by anurag-mehra** [comment]
Ok i understand, but now i have switched desktop environment to mate , I am
not getting the problem
