### ISSUE TITLE
Remove default keybindings for enabling terminal broadcast

### ISSUE THREAD

**Issue by JakubVanek** [gnome-terminator/terminator#40]
Activating terminal broadcast through a key combination could prove very dangerous in certain situations, see previous issue: https://bugs.launchpad.net/terminator/+bug/1872460

**Comment by JakubVanek** [comment]
I think that changing the default setting value is sufficient to prevent this. Only explicitly changed options are saved in the configuration file (at least so it seems on Ubuntu 18.04), so we don't have to deal with rewriting old profiles where the problematic defaults got saved.

**Comment by FernandoBasso** [comment]
I wonder if another further step regarding these keybinding for “broadcasting” would be to leave only two of them, and instead of three we currently have, they would instead toggle the feature! For instance, `Ctrl-Shift-A` would enable “broadcast all” if disabled the, and disable otherwise. The same for “broadcast group”. This way, instead of users having to remember three keybindings, only two would suffice.

As a side note, Tilix uses the same key to toggle the broadcasting, and Tmux, similarly, uses the same `set-window-option synchronize-panes` to toggle the feature on and off. Not that I want to copy those, but it does seem to make sense using a toggle-like thing than having to know a third command to toggle off the broadcasting.

**Comment by mattrose** [comment]
I'm really of two minds about this.  One of the selling points of terminator for me is that there are keybindings for just about everything, but...

1.  Broadcast all doesn't seem like that useful a feature to me. (Happy to hear otherwise)
2.  You make a very compelling argument in the original LP bug because there's no visual indicator that the commands you're sending are being sent to every single open terminal.

I'm tempted to pull this if no-one else has any concerns.

**Comment by FernandoBasso** [comment]
> Broadcast all doesn't seem like that useful a feature to me. (Happy to hear otherwise)

I use it once or twice a day to `cd` all shells to a given directory or to change my `PS1` prompt (I have some functions that go from creating very simple `$ ` prompts to full blown ones displaying git and showing a lot of info). It is a feature I use in a similar way in Tmux too.

> You make a very compelling argument in the original LP bug because there's no visual indicator that the commands you're sending are being sent to every single open terminal.

If you have two or more panes under the same tab, the pane title bars will change color. Perhaps we could work on something more obvious in the future (Tilix displays a little icon on the pane title when “synchronize input” is toggled on, Tmux displays nothing by default and I guess one would have to script something).

**Comment by ohir** [comment]
@FernandoBasso 
> I use it once or twice a day to cd all shells to a given directory or to change my PS1 prompt

This PR is not about removing a possibility to bind. It removes the **default** binding, because this feature is meant for power users only. If you already do know about PS1 you likely will read terminator docs and bind dangerous but useful things for yourself. Novice user may not know about it until after being bitten.

> I use it once or twice

I used it once or twice, then decided that this feature is for me too dangerous to be turned on by a keyboard slip. (Then I added per-terminal environment configuration to my version of terminator for things like a prompt settings). 

This PR is about protecting new users, and IMO it should land in master ASAP.

**Comment by FernandoBasso** [comment]
> This PR is not about removing a possibility to bind. It removes the **default** binding, because this feature is meant for power users only. If you already do know about PS1 you likely will read terminator docs and bind dangerous but useful things for yourself. Novice user may not know about it until after being bitten.

Yeah, I understand that, and I agree users are better off if this feature doesn't have a default and so easy-to-type key binding which can be so easily turned on by accident.

**Comment by mattrose** [comment]
Thanks for the feedback @FernandoBasso.  Given that there is a way to trigger "broadcast all" through the titlebar menu I don't think there's much harm in removing the default keybinding.  The feature is visible regardless.
