### ISSUE TITLE
Allow disabling and resetting keybindings in Preferences

### ISSUE THREAD

**Issue by tomty89** [gnome-terminator/terminator#423]
In Preferences we can only change a keybinding to another value. Would be great if there are buttons for disabling one and resetting one to its default. Making use of right click (menu, or just "cycle") is IHMO fine as well.

**Comment by ifohancroft** [comment]
I don't know if resetting a variable to its default value is possible atm besides deleting the changed bind from the config, but you can unset a keybinding by double clicking it then hitting Backspace.

**Comment by mattrose** [comment]
@ifohancroft is right.

**Comment by patricknelson** [comment]
Regarding disabling: It'd still be neat to have a button at least for _that_ particular feature (since it's not clear how to do it without [reading the docs](https://gnome-terminator.readthedocs.io/en/latest/preferences.html?highlight=keybinding#keybindings) or Googling and then landing here like I just did). 😅
