### ISSUE TITLE
Crash on Terminal resize when using fish

### ISSUE THREAD

**Issue by Benimautner** [gnome-terminator/terminator#458]
**Describe the bug**
When setting the default shell to [fish](https://github.com/fish-shell/fish-shell) and then trying to resize a terminal to a very small window, Terminator will crash. This does not happen every time, but it is easily possible to reproduce.

**To Reproduce**
- install fish `sudo apt install fish`
- change default shell to fish `chsh -s /usr/bin/fish`
- open terminator `terminator`
- open two terminals above each other `STG + SHIFT + O`
- resize using `STRG + SHIFT + ARROW UP / ARROW DOWN`
    - bug seems to occur more often if arrow keys are being held down
- terminator crashes

I can provide a screen capture if one is needed.

**Expected behavior**
No Crash

**Log**
`terminator -d -u -g /dev/null`
[https://pastebin.com/U3GQaJQB](https://pastebin.com/U3GQaJQB)

Most important lines:
```
VTE:ERROR:../src/vteaccess.cc:628:void vte_terminal_accessible_text_scrolled(VteTerminal*, gint, gpointer): assertion failed: (i >= 1)
Bail out! VTE:ERROR:../src/vteaccess.cc:628:void vte_terminal_accessible_text_scrolled(VteTerminal*, gint, gpointer): assertion failed: (i >= 1)
Aborted (core dumped)

```

**Desktop (please complete the following information):**
 - Ubuntu 20.04
 - Linux 5.8.0
 - Desktop environment: KDE

**Additional context**
Bug #153 seems to be related as that user was using fish too.

**Comment by mattrose** [comment]
Judging by the error message, this is an error in the VTE library that Terminator uses.  I think (though I'm not 100% sure) that this is fixed in a later release.  Can you try updating the vte packages to see if that fixes it?

gir1.2-vte-2.91 and libvte-2.91-0

**Comment by Benimautner** [comment]
This has fixed the issue, but I had to compile and install the newest version of vte directly from [source](https://gitlab.gnome.org/GNOME/vte) to get it to work. Thanks for your help!

**Comment by mattrose** [comment]
Yeah, I close issues when the code is pulled into master and tested.  I don't bother waiting until the code makes it into a release.  Having said that, it's about time for a release.

**Comment by Meavel** [comment]
This is my question that I asked chatgpt:

Question: why I download terminator and fish terminal for ubuntu but both combined become one?


ChatGPT said:
​When you install both Terminator and the Fish shell on Ubuntu, you might observe that launching Terminator opens a terminal running Fish within a single window. This behavior occurs because Terminator is designed to manage multiple terminal sessions within a single window, and it uses your default shell for each session.​
[GitHub](https://github.com/gnome-terminator/terminator/issues/458?utm_source=chatgpt.com)

Understanding the Behavior:

Terminator's Design: Terminator is a terminal emulator that allows users to run multiple terminal sessions in a single window by splitting it into multiple panes. Each pane operates as an independent terminal session. ​

Default Shell: When you open a new terminal session in Terminator, it launches your default shell. If you've set Fish as your default shell, each new terminal session in Terminator will start with Fish.​
(Ask Ubuntu)
+3
(Ask Ubuntu)
+3
(Unix & Linux Stack Exchange)
+3

Customizing Shells in Terminator:

If you want to run different shells (e.g., Bash in one pane and Fish in another) within Terminator, you can configure this by setting up custom layouts or profiles:​

Using Layouts:

Open Terminator and right-click anywhere in the terminal window.​
(solveforum.com)
+9
(GitHub)
+9
(Ask Ubuntu)
+9

Select 'Preferences' from the context menu.​

In the 'Layouts' tab, you can create or edit a layout. For each terminal within the layout, you can specify a 'Default command' to run a specific shell. For example, set one terminal's default command to /bin/bash and another to /usr/bin/fish. ​
[Ask Ubuntu](https://askubuntu.com/questions/158159/how-do-i-get-terminator-to-start-up-with-my-custom-layout?utm_source=chatgpt.com)

Using Profiles:

Within the 'Preferences' window, navigate to the 'Profiles' tab.​

Create separate profiles for each shell you want to use.​

Assign the desired shell as the default command for each profile.​

When opening a new terminal or splitting a pane, you can select which profile (and thus which shell) to use.​

Additional Considerations:

Starting Terminator with Specific Shells: You can start Terminator with a specific shell using the command line. For example, to start Terminator with Bash, you can use: terminator -e /bin/bash. ​
(manpages.ubuntu.com)
+1
(Unix & Linux Stack Exchange)
+1

Handling Terminal Resizing Issues: Be aware that combining Terminator with Fish can sometimes lead to issues, such as crashes when resizing the terminal to a very small window. This is a known issue and has been documented in the Terminator [GitHub](https://github.com/gnome-terminator/terminator/issues/458?utm_source=chatgpt.com) repository. ​
GitHub

By configuring Terminator's layouts and profiles, you can effectively manage multiple shells within a single window, tailoring your terminal environment to your workflow preferences.​
