### ISSUE TITLE
Terminator doesn't respect "Hide from taskbar" option

### ISSUE THREAD

**Issue by pluc** [gnome-terminator/terminator#475]
Using a "complex" configuration file (mostly because there's lots of splits), Terminator ignores the "Hide from Taskbar" option. It worked initially, but not won't even work for a simple window.

Configuration file is here: https://gist.github.com/pluc/d911e1a195ab454137a6389afeb21c62

**Describe the bug**
The option to "Hide from Taskbar" is on but Terminator is still shown in task bar.

**To Reproduce**
1. Check the "Hide from Taskbar" option in Preferences

**Expected behavior**
I expected the taskbar not to have Terminator

**Screenshots**
![image](https://user-images.githubusercontent.com/64719/127850529-34ef6e5a-e557-4d97-99ed-22826012ba98.png)
![image](https://user-images.githubusercontent.com/64719/128430085-b52ea774-e243-4a3a-b5fd-7c14a882c32e.png)

**Desktop (please complete the following information):**

 - Debian 11
 - Cinnamon (WM Mutter)
 - Terminator v2.1.0

**Comment by mattrose** [comment]
It looks like your configuration file got messed up at some point:

mattrose@terminator:~/Code/terminator$ python3 terminator -u -g ./config.txt 
ConfigBase::load: config format is not valid
[layouts,Leftbar,child4]: parent is invalid
[layouts,Leftbar,child4]: type is invalid

This may be what's causing the problem.

**Comment by pluc** [comment]
@mattrose running the same command locally didn't trigger an error:

```
:~/.config/terminator$ terminator -u -g ./config 

** (terminator:556825): WARNING **: 10:07:46.225: Binding '<Control><Alt>a' failed!
Unable to bind hide_window key, another instance/window has it.
<window.Window object at 0x7fb861826380 (terminatorlib+window+Window at 0x2792280)> is not in registered window list
```

Maybe it's because I had edited out some privacy things in it. Either way, I put a new config up at the same link if you want to try that.,

**Comment by mattrose** [comment]
Hmm, when I try using that config, the window does not show up in the GNOME taskbar, or the Show All Applications (Super Key) screen.

**Comment by pluc** [comment]
I don't think it's a config issue, it happens regardless of the window/profile/layout


![Peek 2021-08-06 10-28](https://user-images.githubusercontent.com/64719/128525733-5c4cc8ca-8e7d-49f1-9c9b-dfdb58ef316f.gif)

**Comment by mattrose** [comment]
The code for hiding window from the taskbar hasn't changed since implementation.  Was there a cinnamon update or something that could be causing this?  As I said, it works in GNOME.

**Comment by pillmuncher** [comment]
I played around with the Terminator config file yesterday and now I have the same problem on Budgie (Solus Linux). Nothing I tried to fix it seems to work. I even played around with the Terminator code, and it looks like the terminatorlib.window.Window.set_skip_taskbar_hint(value) method inherited from Gtk.Window is somehow broken, since whatever value I provide, nothing changes. PyPi says that the newest Version of PyGObject is from March. Why it suddenly changed its behavior - who knows. I opened an issue on Gnome's gitlab, see https://gitlab.gnome.org/GNOME/pygobject/-/issues/485. I'll report back when I know more.

**Comment by pillmuncher** [comment]
I think I found the bug. Except, it's not a bug. Instead of 
```
        if self.hidebound:
            self.set_hidden(hidden)
            self.set_skip_taskbar_hint(skiptaskbar)
        else:
            self.set_iconified(hidden)
```

in terminatorlib.window.py lines 174ff, one could write this:

```
        self.set_skip_taskbar_hint(skiptaskbar)
        if self.hidebound:
            self.set_hidden(hidden)
        else:
            self.set_iconified(hidden)

```
Now the icon is hidden as expected.

But this is bad. As it happens, the shortcut for hiding the window on my computer was already in use by another application, same as in @pluc's case, so Terminator failed to acquire that shortcut. The original code above said that the icon is only hidden from the taskbar if such a shortcut exists in Terminator. But why make hiding the icon from the taskbar dependent on some key binding that hides the window? The reason behind this is that a hidden window without an icon to un-hide again it is somewhat stupid. So, the real solution is to find a shortcut that is available. Maybe the docs should say something about this. I, at least, have found nothing there.

**Comment by mattrose** [comment]
Thanks so much for looking into this and coming up with an accurate reproduction scenario.  I think we should probably spit out an error in this case, just so that it's clear that we're ignoring this on purpose.   I think even I have gotten confused in the past about whether or not it should work.
