### ISSUE TITLE
Monospace Bold isn't working

### ISSUE THREAD

**Issue by jJit0** [gnome-terminator/terminator#497]
Hi,

I set a Monospace Bold 13 font into my default profile, but it doesn't work.
The terminal displays a normal Monospace font, and not a **BOLD** one

As a matter of fact, none of the **BOLD** fonts in my entire list is working at all, is there any explaination for this ?

I'm using Terminator 2.1.0, Kali 2020.2 and Gnome Environement.

Here is my config file
```[global_config]
  focus = system
  geometry_hinting = True
  broadcast_default = off
  scroll_tabbar = True
  title_hide_sizetext = True
  inactive_color_offset = 0.5
  enabled_plugins = CustomCommandsMenu, ActivityWatch, InactivityWatch, MavenPluginURLHandler, Logger, LaunchpadBugURLHandler, LaunchpadCodeURLHandler, APTURLHandler
  always_split_with_profile = True
  title_font = Sans 8
  putty_paste_style_source_clipboard = True
[keybindings]
  line_up = <Primary><Alt>Up
  line_down = <Primary><Alt>Down
  next_tab = <Shift><Alt>Right
  prev_tab = <Shift><Alt>Left
  help = <Alt>F12
[profiles]
  [[default]]
    audible_bell = True
    background_darkness = 0.95
    backspace_binding = automatic
    delete_binding = automatic
    cursor_shape = ibeam
    cursor_color = "#ef2929"
    cursor_color_fg = False
    font = Monospace Bold 13
    foreground_color = "#00ff00"
    show_titlebar = False
    scrollbar_position = hidden
    scrollback_infinite = True
    palette = "#000000:#e71010:#36a347:#d4d71b:#00b2ff:#b427cb:#00fff0:#eeeeec:#888a85:#ff0000:#00ff00:#ffff00:#0066ff:#fa00ff:#1acfc4:#ffffff"
    use_system_font = False
    copy_on_selection = True
[layouts]
  [[default]]
    [[[child1]]]
      parent = window0
      profile = default
      type = Terminal
    [[[window0]]]
      parent = ""
      type = Window
[plugins]

**Comment by mattrose** [comment]
If you go into Preferences -> Profles -> default -> Colors, at the bottom of that preferences pane, there is a "Show bold text in bright colors" that you should enable.  This will, inexplicably, let you select bold fonts again.  Yes, I actually had to research this a whole bunch because it makes no sense.

This is currently a "feature" of the newest version of vte.  See https://gitlab.gnome.org/GNOME/vte/-/commit/868602fdbe590761418f6be1242b625d494078b1 for the commit and https://gitlab.gnome.org/GNOME/vte/-/issues/323 for discussion about this.
