### ISSUE TITLE
How to run Terminator 2+ under Cygwin on Windows 10 ?

### ISSUE THREAD

**Issue by mray271** [gnome-terminator/terminator#523]
**Is your feature request related to a problem? Please describe.**
Cygwin distributes on Terminator 0.98 which depends on (by now) very deprecated Python 2.7 is buggy and doesn't run reliably.
Running it requires hacking the /usr/bin/Terminator script and forcing it to run under Python2.7 since Python 3.8 is the default under current Cygwin. Also various .dlls appear incompatible 

**Describe the solution you'd like**
I'd like to be able to run Terminator on Windows using Cygwin. Are there recommended ways of doing this?  Are there plans to distribute or make available a Cygwin package for Terminator 2.0

**Describe alternatives you've considered**
Guake on Cygwin is a similar terminal manager, but on Cygwin is also currently stuck at Python 2.7 support.

**Additional context**
Being able to run Terminator on Windows is very helpful for system administration of Linux servers when your primary station is required to be Windows.

Thank you

**Comment by mray271** [comment]
Running through the installation instructions in INSTALL.md, the process gets stuck as psutil dependency which is not supported in Cygwin.   Apparently there is a spat among developers preventing a Cygwin port pull request for psutil support:  https://stackoverflow.com/questions/69149920/unable-to-import-psutil-in-python3-with-cygwin-importerror-no-os-specific-modu

**Comment by mattrose** [comment]
Did you try running `python3 -m pip install --upgrade psutil` ?  That sounds like it may get around the problems you're having with installing it.

We don't actually use psutil that much in terminator, and I could probably hack around it for cygwin.  I'll see if I can download cygwin on my windows machine and give it a go.

Honestly I've always run terminator through WSL2 since I took over, so I'm amazed it's this close to working on cygwin.

**Comment by mattrose** [comment]
To answer your other question.  We have no input on what gets built as a cygwin package.  If you want cygwin to support newer versions of terminator, you need to talk to them.
