### ISSUE TITLE
Moving Cursor Word By Word using ALT + Arrows

### ISSUE THREAD

**Issue by iis2h** [gnome-terminator/terminator#566]
Good Day,
I'm facing a trouble I was using default terminal and I switch to Terminator. 
I can't move the cursor word by word using `alt + arrows` instead of `alt + b or c` is there anyway to do it?

**Comment by Vulcalien** [comment]
Hello! `Alt + arrows` are by default used to navigate the many terminals in a terminator window. However, that can be disabled, so that the behavior is the "default" one. In my system doing `alt + arrows` just prints "A B C D" in any terminal I've tried.

To disable the keys:
- Right click
- Preferences
- Keybindings
- Search for go_[up/down/left/right]
- Click and disable with backspace

If this doesn't work and you haven't already, I think such a behavior could be obtained configuring in the shell.

**Comment by iis2h** [comment]
it's ok I will be ok with them. But I want to change `alt + c` and `alt + b` I didn't find them in the keybindings, I would like to change them to any other key with `alt` except `c` and `b`

**Comment by iis2h** [comment]
I have disabled `CTRL + Arrows` in my Mac shortcuts to use it in Virtual Machine. By default Kali terminal uses `CTRL + Arrows` to move cursor word by word in other hand MacOS uses them to switch between Desktops . So, I have to choose between them. thanks
