### ISSUE TITLE
-H, --hidden not working on Ubuntu KDE desktop

### ISSUE THREAD

**Issue by SkirmantasK** [gnome-terminator/terminator#567]
Terminator starts not hidden despite using -H or --hidden parameters

Start terminator with -H or --hidden parameter

 - Ubuntu 
 - 20.04.3 LTS
 - KDE desktop

**Comment by Vulcalien** [comment]
Hi! There are two possibilities I'm thinking about.
1. Are you running `terminator --hidden` from a terminator terminal?
2. Are you using wayland?

**Comment by SkirmantasK** [comment]
> Hi! There are two possibilities I'm thinking about.
> 
>     1. Are you running `terminator --hidden` from a terminator terminal?
> 
>     2. Are you using wayland?

1. No, from konsole or run using alt+f2
2. No, my session type is x11

**Comment by Vulcalien** [comment]
I tested this on a VM with KDE and I noticed the behavior.

Do you get an error message like this?
`Unable to bind hide_window key, another instance...`

If it's the case, then it's a bug that was fixed in #510.
I can't really understand why this wouldn't work in KDE while it would work fine in GNOME.

I tried versions 2.1.0 and 2.1.1, both do not work. The repository version with the fix does.

**Comment by mattrose** [comment]
I'm gonna take @Vulcalien's word that this is fixed in master, closing
