### ISSUE TITLE
Custom Commands NOT Working in Linux Mint 20.3

### ISSUE THREAD

**Issue by nowindows** [gnome-terminator/terminator#573]
After installing Linux Mint 20.3 (previously used 19.3) I found that the "Custom Commands" don't work.  When I right click to Custom Commands/Preferences all of my previous Custom Command are there and are enabled but don't work anymore (no text is copied to terminator window upon selection).

**Comment by Vulcalien** [comment]
Can confirm. I tried in a Linux Mint VM.

Looking at the error messages, it seems a problem with Vte. My guess is that that package was updated and since Terminator wasn't (Mint still ships 1.91 or 1.92) now that feature is broken.

The bug, however, should be fixed now (#291).
I tried running the repository version, and it works.

You could install Terminator manually or wait for the Mint maintainers to update (or patch) the package.

**Comment by nowindows** [comment]
Thank you! It's working now.
