### ISSUE TITLE
Can not switch input methods with fcitx in terminator

### ISSUE THREAD

**Issue by mjw10086** [gnome-terminator/terminator#667]
Package: terminator
Version: 2.1.2-1
system: Linux kali 5.19.0-kali2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1kali2 (2022-10-10) x86_64 GNU/Linux

Gnome 43.0 

Composed key such as ctrl + shift + o works, but shift or ctrl + space can not switch input method in 2.1.2-1, but 2.1.0-2 is OK.

**Comment by mattrose** [comment]
Can you be a little more clear?

**Comment by mjw10086** [comment]
@mattrose my situation is that I can't input Chinese in terminator with fcitx

those code may lead fcitx not work in terminator, after I comment those, It works. I don't know how to fix that, it seems that is relative with another issue?
```
# Deleting env variable fixes double char problem when broadcasting (#78)
# Only delete if it exists, or exception occurs
if os.environ.get("GTK_IM_MODULE") is not None:
    del os.environ["GTK_IM_MODULE"]
```

**Comment by mattrose** [comment]
Ugh, there is some conflict between IBus and Terminator broadcasting that I have been trying to track down for years now.  Every time I think I have a solution, it pops back up again

**Comment by shilkazx** [comment]
Same problem after update terminator to 2.1.2-1 on Archlinux amd64. In general, delete GTK_IM_MODULE env variable would cause fcitx malfunction.

**Comment by shilkazx** [comment]
> Ugh, there is some conflict between IBus and Terminator broadcasting that I have been trying to track down for years now. Every time I think I have a solution, it pops back up again

If there is some comflict between ibus and terminator, but nothing abnormal between fcitx and terminator. Could you please temporary fix it by add a condition that check whether fcitx/ibus is used(check whether or not GTK_IM_MODULE=fcitx), and do not del the env variable in fcitx circumstance.

**Comment by mattrose** [comment]
> Could you please temporary fix it by add a condition that check whether fcitx/ibus is used(check whether or not GTK_IM_MODULE=fcitx), and do not del the env variable in fcitx circumstance.

Yeah, but that wouldn't fix #670.

Have you deleted the offending lines from your code?

If so, can I ask you to run a quick test for me?

Can you try setting up broadcasting to a different terminal, and see if you get doubled characters when typing characters into the terminal?

**Comment by shilkazx** [comment]
> > Could you please temporary fix it by add a condition that check whether fcitx/ibus is used(check whether or not GTK_IM_MODULE=fcitx), and do not del the env variable in fcitx circumstance.
> 
> Yeah, but that wouldn't fix #670.
> 
> Have you deleted the offending lines from your code?
> 
> If so, can I ask you to run a quick test for me?
> 
> Can you try setting up broadcasting to a different terminal, and see if you get doubled characters when typing characters into the terminal?

I'd like to try the modification I mentioned before. But could you explain the meaning of "broadcasting to a different terminal"? I've checked #670 and #78. It seems that #670 is not related to the broadcasting problem. Another thing that is worth mentioning here is I use both terminator and fcitx for such a long time, at least starting before #78 occurred, but I never met bug #78 or something like that.
The temporary fix I suggest before might be a semi-permanent solution because people who use fcitx usually focus on CJK character input but not Latin or European language, so

**Comment by mattrose** [comment]
However, if I change the code so `GTK_IM_MODULE=fcitx` gets left in place, but all other values get removed, C-cedilla will get removed, and bug #670 will remain.

By Doubling, the screenshot at the top of #78 explains it pretty well.  when you broadcast your input to multiple terminals ( 
https://terminator-gtk3.readthedocs.io/en/latest/grouping.html has a good guide to setting it up ), your input will be sent twice to each terminal, rather than each one.

**Comment by mattrose** [comment]
Can you test out the code in #674 and see if it fixes the problem

**Comment by mattrose** [comment]
Should be fixed in master now.

**Comment by shilkazx** [comment]
Sorry for the late reply, I'll feedback in #674 thread.
