### ISSUE TITLE
A translucent separation occurs between terminals

### ISSUE THREAD

**Issue by mccarlosen** [gnome-terminator/terminator#687]
![image](https://user-images.githubusercontent.com/8524361/204007411-b652f084-3dff-4a8f-a584-74f67141ebbe.png)

I use the Linux Mint 21 Cinnamon operative system.

**Comment by mattrose** [comment]
This is because the theme you're using does not have the necessary elements to render the separator, so it doesn't render it properly. 

This is a problem with those themes not specifying the color of the separators, therefore, GTK renders the separators as transparent. I'm loathe to add more complexity to the preference pane to fix an issue with incomplete GTK themes. There are good instructions in https://github.com/gnome-terminator/terminator/issues/293 for fixing the CSS for this property manually, and you could push the changes to your favourite theme so that it would fix this problem for everyone who uses that theme.
