### ISSUE TITLE
clipboard - putty style paste - copy using external app - cant paste into terminator

### ISSUE THREAD

**Issue by flipkickmedia** [gnome-terminator/terminator#749]
Before opening an issue, please try starting terminator with an empty config
file, by issuing `terminator -u -g /dev/null` and see if it starts normally.

If it does, and you still want to open the bug, then please attach the
config file, usually found at `$HOME/.config/terminator/config` to the issue

Fill out as many of these fields as you can

**Describe the bug**
When PuTTY paste is activated, other apps don't see this clipboard content.

**To Reproduce**
I have VSCode open, when I copy something (ctrl+x or using the menu) I am unable to paste this into terminator using the right mouse button.

If I select some text in terminator I am able to press the right mouse button and paste into another terminator, even if this is inside another window.  If I move over to VSCode, the previous clipboard content is pasted.

Tried with no config. Same result.

**Expected behavior**
Id like to be able to select and then paste this into another window, in this case VSCode and vice versa

I understand there are two clipboards, can we keep both of them synced please when PuTTy style paste is activated?

**Screenshots**
![image](https://user-images.githubusercontent.com/15732784/233942072-13b4de60-8813-4faa-8b9d-edf4b6e50512.png)

**Desktop (please complete the following information):**
Ubuntu 22.10
[config.txt](https://github.com/gnome-terminator/terminator/files/11308383/config.txt)

**Comment by Vulcalien** [comment]
The reason for that is that, when pasting using right-click, you are pasting the `Primary Selection`. That is usually filled with text selected using the mouse.

> I understand there are two clipboards, can we keep both of them synced please when PuTTy style paste is activated?

What I suggest you do is select `Clipboard` for PuTTY style paste, so that the right-click pastes the Clipboard's contents.
That solves the pasting part, but you can also copy directly to the `Clipboard` when selecting text. (Preferences > Profiles > General > Copy on selection)
This way, Terminator will only use the Clipboard.

As long as any other application copies to the Clipboard, that should be enough.

**Comment by flipkickmedia** [comment]
Lets try this out.....

**Comment by Vulcalien** [comment]
Perfect!
