### ISSUE TITLE
There are still translation commits to launchpad

### ISSUE THREAD

**Issue by DarthGandalf** [gnome-terminator/terminator#85]
Instead of here.
E.g. http://bazaar.launchpad.net/~gnome-terminator/terminator/trunk/revision/1779

**Comment by mattrose** [comment]
I think there's a launchpad translation team that adds translations semi-automatically, but I have no idea how that works.  It's one of the reasons I didn't want to move the .po files in #13.  I have no idea if we can ask them to commit to github rather than launchpad, or if there's a way to automatically transfer those to Github PRs.  It's a valuable service, I think.

**Comment by DarthGandalf** [comment]
There are 2 parts of it:
* generating .pot from sources and uploading them to somewhere, and it's not launchpad, because https://translations.launchpad.net/terminator is empty
* commiting updated .po back to source

I tried to find where the translations are done for terminator, but couldn't find the place.

For ZNC I configured it with combination of Crowdin and Jenkins: https://github.com/znc/znc/blob/master/.ci/Jenkinsfile.crowdin
Perhaps you can try to make it a similar setup.

**Comment by lazyfrosch** [comment]
I disabled Translations on Launchpad the day I got access. Those old commits will be merged in a PR.

For the future we will use transifex, introduction and documentation pending with #90

**Comment by DarthGandalf** [comment]
Ah, cool!
