### ISSUE TITLE
[Feature Request] Add SelectAll function

### ISSUE THREAD

**Issue by songhtdo** [gnome-terminator/terminator#851]
Thanks for the very useful software.

In the operation, it is often necessary to record the operation in the process to the notepad. 
Although the mouse scrolling selection can achieve the function of full selection, it is inconvenient when the number of scrollable lines is relatively long. If there is a full selection function, you can greatly accelerate the operation or directly add the function of copying all text to the system clipboard, which can be better
Thank you very much!

**Comment by songhtdo** [comment]
[Feature Request]
I want to add a search function to locate the text content of the window.

**Comment by vssdeo** [comment]
Hi @songhtdo not sure if it would help but I had once created a plugin to test my keybindings. After enabling the plugin:
 1. You can press `<Shift> Up` or `<Shift> Down` to get clipboard 
 2. Then you can select using arrow keys or `<Ctrl>A `. 
 3. Pressing `<Shift><Control>c `will copy and close the window then you can paste it.

- I had not submitted this plugin since, later on it will be supported by base vte terminal, but it might help now. Also we can also do what you want directly also.

Ref: https://github.com/vssdeo/terminator/tree/new-selecting-text-with-keyboard-shift-up-shift-down

**Comment by vssdeo** [comment]
Thanks for your feedback, I surely agree that this should be part of core functionality, with lesser key presses for select all. I just gave an option for time being since it was lying around. 

Let me add this to main code base or may be add select all to the plugin without touching main code.

**Comment by vssdeo** [comment]
Hi @songhtdo just to update. I have made changes to the brach referenced above, so  now when plugin is enabled you can use `<Ctrl>a` to copy the entire buffer and then paste as usual using `<Shift><Ctrl>v` try it out if it works for you.

**Comment by songhtdo** [comment]
hello.
I placed the mousefree plugin of the new selecting text with keyboard shift up shift down branch in the plugins directory of the terminator, but it did not appear in the plugin list or shortcut key list after running the terminator again.
I think we can put this issue aside for now.
Thank you very much again!

**Comment by vssdeo** [comment]
Ok if you get time you can check logs in debug mode if you see any error message. I will also check and fix if any issue and have this complete. Better have things fixed :)  Cheers !

**Comment by songhtdo** [comment]
hi, 
For this question the other day, I found two plugins that seem to be just what I need.
https://github.com/egroeper/terminator-plugins
Thank you again.
