### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by baryluk** [gnome-terminator/terminator#891]
I use terminator 10 hours a day for last 15 years.

I never had a real major issue, other than few minor bugs, so never really considered contributing code. (I have libvte fork with sixel support, and it works out of the box with Terminator). For some time I considered making Terminator wayland compatible, but it was not high prio, and it looks it supports wayland natively now anyway. Thanks.

Other than that, is there maybe way to do dontations, sponsorship, to make sure project is alive?

Not sure how would that work with github organisation and multiple people, but at least maybe some CI/CD costs can be covered this way, or some areas extended?

Feel free to close, if you think there is no need or it is a bad idea.

**Comment by Fryboyter** [comment]
> Other than that, is there maybe way to do dontations, sponsorship, to make sure project is alive?

I cannot speak for this project. I'm just a former user of Terminator. But often the problem is not the financial situation but simply the time you have available.

Many projects are not developed full-time but in one's spare time. And in your free time you often have more important things to do. For example, spending time with friends or family.

In such a case, the only solution I can think of is that several developers have the rights to accept pull requests and publish new versions. However, you would have to trust them very much. And in certain cases, you would have to accept decisions that you might not agree with yourself. From my point of view, this is not an easy decision.

**Comment by mattrose** [comment]
@baryluk Thank you so much for your kind comments.  It means a lot to me that you took the time and reached out to let us know that the work we put in is appreciated and used.  Markus and I agreed when we took over that we would not take money for the project.  It's just not something the project needs, as it stands.  It doesn't cost us a cent to run, so we can't really accept money for it.  Contributions in time are much more appreciated.  Everything from ensuring the documentation matches what is in the code (which I know for sure isn't currently the case), to taking a stab at bugfixes and keeping up with advances in GTK3, VTE and Python to new feature development.

@Fryboyter you are definitely right that this is developed in my spare time, and I have a lot of other obligations that come before this.   I appreciate every contribution that has been made over the past 5 years, as those contributions have been what has driven the project forward.  I would love to give more developers commit access, but to be honest, no-one has asked.   There are a few contributors who make PRs that I barely check, because I trust them and they have a history of successful PRs, but nobody has asked for full commit access.  If you're personally interested in such things please let me know.

One of the things I'm currently working on in the background is the GTK4 migration, but that touches **so** much of the code that it's still not in a usable state, even after a week's worth of work on it, spread out over the past 6 months.

**Comment by sjoblomj** [comment]
> I use terminator 10 hours a day for last 15 years.
> 
> I never had a real major issue, other than few minor bugs, so never really considered contributing code. (I have libvte fork with sixel support, and it works out of the box with Terminator). For some time I considered making Terminator wayland compatible, but it was not high prio, and it looks it supports wayland natively now anyway. Thanks.
> 
> Other than that, is there maybe way to do dontations, sponsorship, to make sure project is alive?
> 
> Not sure how would that work with github organisation and multiple people, but at least maybe some CI/CD costs can be covered this way, or some areas extended?
> 
> Feel free to close, if you think there is no need or it is a bad idea.

In what state is your sixel libvte fork? Is it available somewhere? Not much seems to be happening at [Gnome VTE](https://gitlab.gnome.org/GNOME/vte/-/issues/253); the ticket to implement Sixel has been open for close to four years by now.

**Comment by baryluk** [comment]
@sjoblomj Not, really fork. Just clone of the libvte, with the patches from that issue, and SIXEL enabled by default (change some `#define` there), then compile and install, and use.

It works, and had no big issues. (I primarly use it with `gnuplot`). It is not perfect (i.e. memory usage can be sometimes high, or scrolling can be slow, when one has long history, and even just few image buffers), but not too bad.

**Comment by mattrose** [comment]
Just to poke my head in here to say that SIXEL support is in the latest versions of terminator and vte, so if you're running a distro that keeps up with upstream, you should be able to get rid of your vte fork, and I added SIXEL support in #770
