### ISSUE TITLE
Keybindings for cursor/caret movement 

### ISSUE THREAD

**Issue by drschwabe** [gnome-terminator/terminator#896]
There is currently no command/ability to set keybind for cursor movement.    I like mine set to ALT + IJKL for example as i don't have to move my hand off the homerow to change cursor/caret position.

**Comment by egmontkob** [comment]
In the world of terminal emulation, the cursor is not in the control of the terminal emulator, the cursor is in the control of the applications that run inside (e.g. your shell, text editor etc.). The terminal emulator has to obey the instructions it receives from these apps. Forcingly moving the cursor away would lead to display corruptions in pretty much every application.

You'll have to configure all the terminal-based applications you're using for these keys.

What a terminal emulator _could_ theoretically do is to "lie", e.g. if you press Alt + I then instead tell to the application that you pressed the Up arrow. But this would, of course, make it impossible for an app to handle Alt + I for its own purposes, e.g. to treat it as a shortcut key, even in a context where the Up arrow doesn't make sense.

I'm not a Terminator developer so I cannot tell whether this amount of configurability is a project goal, I only suspect it's most likely not. Could be interesting to see if you can define a keyboard layout for your X11 or Wayland session where these Alt + keys are defined like this.

**Comment by egmontkob** [comment]
> I am comfing from kitty and it's a feature; these lines in kitty.conf do the trick:

That's exactly what I suggested here:

> What a terminal emulator _could_ theoretically do is to "lie", e.g. if you press Alt + I then instead tell to the application that you pressed the Up arrow.

So apparently Kitty is one of those terminals that let you do this.

---

> > The terminal itself should not have the ability to control the cursor.
> 
> I don't necessarily agree, I see it as a parent/child relationship where the parent should have optional overrides. IMO the ideal terminal provides a way to optionally override keystrokes

You guys are talking about different things.

Overriding the input keys, as seen in Kitty, is okay(ish, but might come with unexpected behavior at some places).

Overriding the cursor position is not okay. It would lead to a disaster. Not just utter display corruptions as I mentioned earlier, but more importantly, the app wouldn't know about it and e.g. the text editor wouldn't actually insert the characters at the position you wanted to. Absolutely no-go in the terminal world.

---

Back to the idea of overriding the input keys.

You have to understand that the behavior might not be always perfect. For example an app might present a context where the Up/Down arrows don't do anything, however, there's a word with the letter I underlined, acting as a mnemonic, Alt + I supposedly activating that menu entry. You press Alt + I and the given action does not get executed because the app received the now-useless Up keypress instead.

If you wish _all_ your applications inside the terminal, in _all_ of their contexts, even where it doesn't make sense, to have this Alt + I -> Up mapping, then I'm wondering: why is it limited to the terminal emulator, what makes the terminal so special, wouldn't you want to have this feature in all your graphical apps too? Because it sounds to me that an X / Wayland level keyboard definition would probably be a better solution.
