### ISSUE TITLE
Suddenly lagging on gnome4 

### ISSUE THREAD

**Issue by W-M-D** [gnome-terminator/terminator#899]
If it does, and you still want to open the bug, then please attach the
config file, usually found at `$HOME/.config/terminator/config` to the issue

[global_config]
[keybindings]
[profiles]
  [[default]]
    background_color = "#002b36"
    font = AnonymicePro Nerd Font Mono Bold 10
    foreground_color = "#839496"
    scrollback_infinite = True
    palette = "#073642:#dc322f:#859900:#b58900:#268bd2:#d33682:#2aa198:#eee8d5:#002b36:#cb4b16:#586e75:#657b83:#839496:#6c71c4:#93a1a1:#fdf6e3"
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
[plugins]

Fill out as many of these fields as you can

**Describe the bug**
input lag during switching dirs auto complete, etc doesn't show up in gnome terminal 

**To Reproduce**
Steps to reproduce the behavior: i'm not sure 

**Expected behavior**
no lag ?

**Screenshots**

**Desktop (please complete the following information):**
Linux IPhone-XII 6.8.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000 x86_64 GNU/Linux

 - Version terminator 2.1.3

 - Display Technology: 11

**Additional context**
Sometimes it stops lagging i have no idea wtf

**Comment by egmontkob** [comment]
I'm wondering if it's the same as https://gitlab.gnome.org/GNOME/gnome-terminal/-/issues/8070, and whether my suspicion of `mutter` being the culprit is correct or not (https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/2054510, but non-Ubuntu might also be affected if upstream mutter received the faulty fix and it arrived to your distro).

**Comment by egmontkob** [comment]
Looks like it's https://gitlab.gnome.org/GNOME/mutter/-/issues/3384.

**Comment by campescassiano** [comment]
Same issue here, it started a few days ago.

When I hit the arrow "up" to see the last command, or if I hit "ctrl+R" to recursively search for commands, it is very noticeable the lag.

On the default terminal, I do not experience any lags.

**Comment by cfgnunes** [comment]
I've found a workaround to fix this:

I conducted a fresh installation of Ubuntu 22.04.4 and subsequently marked specific packages for holding using the following commands:

$ sudo apt-mark hold gir1.2-mutter-10
$ sudo apt-mark hold libmutter-10-0
$ sudo apt-mark hold mutter-common

Following this, I proceeded to update all packages.
So, I'm currently utilizing version "42.9-0ubuntu5" of the mutter packages, instead of version "42.9-0ubuntu7."

**Comment by bkolligs** [comment]
I've got this problem as well.

**Comment by mattrose** [comment]
Not a terminator issue, tho, so there's nothing I can do to fix this.  According to ubuntu, this bug is now fixed so give it aniother try after updating to the latest gnome-mutter

**Comment by egmontkob** [comment]
Ubuntu updates in progress, not yet released (but hopefully pretty soon now).

**Comment by campescassiano** [comment]
Few days ago after an `apt-get upgrade`  there was some mutter stuff updated.

Now everything works fine here.

Here is my current mutter version:

```bash
mutter --version
mutter 42.9
```

Not sure if it was updated or not, but I just remember of reading `mutter` in the list of packages to be updated, and after this I do not see the issue happening anymore.
