### ISSUE TITLE
provide a versioned release

### ISSUE THREAD

**Issue by cheese1** [gnome-terminator/terminator#907]
as the last release is from march 2023, it would be great to have a new release.
eg distributions (eg fedora) would pick the new version, which fixes eg #776 without the need to track all issues and fixes.

https://bugzilla.redhat.com/show_bug.cgi?id=2207779 states that the issue can only be fixed upstream.

yours
joe

**Comment by timur-g** [comment]
Basically the same as #906.

**Comment by mattrose** [comment]
https://github.com/gnome-terminator/terminator/releases/tag/v2.1.4

That bugzilla ref is funny too, because Dom knows he could have backported the patch, I'm guessing he just didn't want to bother to patch it, and then pull the patch out for the next release.  Easier to just get people to bug me :)

I'm also on the Fedora Maintainer team for Terminator, and I'm working on rebuilding my Fedora desktop for building Fedora packages, so hopefully I can get this into Fedora soon.

**Comment by cheese1** [comment]
finaly fixed in fedora 40 
https://bodhi.fedoraproject.org/updates/FEDORA-2024-5006d68fb6

**Comment by dmaphy** [comment]
> https://github.com/gnome-terminator/terminator/releases/tag/v2.1.4
> 
> That bugzilla ref is funny too, because Dom knows he could have backported the patch, I'm guessing he just didn't want to bother to patch it, and then pull the patch out for the next release. Easier to just get people to bug me :)
> 
> I'm also on the Fedora Maintainer team for Terminator, and I'm working on rebuilding my Fedora desktop for building Fedora packages, so hopefully I can get this into Fedora soon.

Actually I'm busy with my daily work and family (got a 15 month old boy around here now) and just noticed today there is a release and this issue was fixed. So in case you need me, better ping me directly via mail. :)

**Comment by mattrose** [comment]
> Actually I'm busy with my daily work and family (got a 15 month old boy around here now) and just noticed today there is a release and this issue was fixed. So in case you need me, better ping me directly via mail. :)

Sorry Dom, I couldn't resist teasing you.  As this bug proves, I am the last person who should be criticizing people for letting things slide a bit 😄 

I know how much time a toddler takes up, congratulations and good luck!
