### ISSUE TITLE
terminator[4834]: segfault at 0 ip 0000791eff7276f4 sp 00007ffcb2bd7698 error 4 in libpango-1.0.so.0.5200.1

### ISSUE THREAD

**Issue by th0ma7** [gnome-terminator/terminator#961]
**Describe the bug**
When using terminator to access lxc containers for compiling, at some point all my terminator windows ends-up being killed.  That has started relatively recently and "seems" to hapen during higher loads (i.e multiple parallel builds being invoked within lxc container)?

I was able to get a `dmesg` log:
```
[  612.850908] terminator[4834]: segfault at 0 ip 0000791eff7276f4 sp 00007ffcb2bd7698 error 4 in libpango-1.0.so.0.5200.1[791eff715000+39000] likely on CPU 6 (core 0, socket 0)
[  612.850929] Code: 00 00 00 0f 1f 00 f3 0f 1e fa e9 c7 f0 fe ff 0f 1f 80 00 00 00 00 f3 0f 1e fa e9 97 ea fe ff 0f 1f 80 00 00 00 00 f3 0f 1e fa <48> 8b 07 ff a0 88 00 00 00 0f 1f 00 f3 0f 1e fa 48 8b 07 ff a0 90
```

**To Reproduce**
kick-off parallel builds within LXC.  Never occured otherwise.

**Expected behavior**
Obviously to stay open - currently testing with konsole just to check if a similar pattern hapens which would be outside from terminator.  Also tempted at migrating to 24.10 which may have the latest version of terminator?

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS or Linux Distribution: ubuntu
 - Version 24.04.1
 - Display Technology: presuming Wayland, can't tell anymore.

**Additional context**
I love terminator, by far my favorite shell since years, thnx for the awesome work :)

**Comment by mattrose** [comment]
This looks like either:

a) most likely:  a memory allocation error in libpango, which is, IIRC, the library used for font rendering
b) less likely: bad RAM in your desktop.

Going to 24.10 could fix this if it's a libpango problem.

Testing with Konsole successfully will likely rule out hardware, as Konsole, afaik, uses the Qt font-rendering lib and not libpango.   If you want to try another test, you could use something like Tilix or gnome-terminal, both of which use the same font-rendering engine.

Either way, this is not something that can be fixed in Terminator, so I'm going to close this bug here.  If you want to open a bug on pango, or need any other help, I still get comments on this, or you can reach me on matrix in https://matrix.to/#/#gnome-terminator_community:gitter.im

**Comment by th0ma7** [comment]
confirmed, it does not have this sympton using qt-based konsole, although it does using gnome terminal.

I did upgraded to 24.10, haven't encountered the issue yet... although I was using terminator when invoking `do-release-upgrade` which ended-up busting before the end of the upgrade.  Gladly I was able to recover easily as it was close to the end :shrug:
